#!/usr/bin/env bash
#
# Install felipe-parra/my-agent-skills into a target repository.
#
# Copies Claude Code skills into .claude/skills/ and concatenates the
# standards/ directory into a single AGENTS.md at the target root.
#
# Usage:
#   ./install.sh [TARGET_DIR]
#   curl -fsSL https://raw.githubusercontent.com/felipe-parra/my-agent-skills/main/install.sh | bash -s -- .
#
# Environment variables:
#   STANDARDS_REPO  Default: https://github.com/felipe-parra/my-agent-skills
#   REF             Git ref (branch, tag, or SHA). Default: main
#   FORCE           Set to 1 to overwrite local edits to AGENTS.md without prompting.
#
set -euo pipefail

STANDARDS_REPO="${STANDARDS_REPO:-https://github.com/felipe-parra/my-agent-skills}"
REF="${REF:-main}"
FORCE="${FORCE:-0}"
TARGET="${1:-.}"

if [[ ! -d "$TARGET" ]]; then
  echo "✗ Target directory '$TARGET' does not exist." >&2
  exit 1
fi

TARGET="$(cd "$TARGET" && pwd)"

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

echo "→ Fetching my-agent-skills @ ${REF}"

# Prefer a shallow git clone (works everywhere git is installed).
# Fall back to a tarball download if git is unavailable.
if command -v git >/dev/null 2>&1; then
  git clone --depth 1 --branch "$REF" "$STANDARDS_REPO" "$TMP/src" \
    >/dev/null 2>&1 || {
      # --branch fails on bare commit SHAs; retry with fetch + checkout.
      rm -rf "$TMP/src"
      git clone "$STANDARDS_REPO" "$TMP/src" >/dev/null 2>&1
      git -C "$TMP/src" checkout "$REF" >/dev/null 2>&1
    }
  RESOLVED_SHA="$(git -C "$TMP/src" rev-parse HEAD)"
elif command -v curl >/dev/null 2>&1 && command -v tar >/dev/null 2>&1; then
  # GitHub tarball — works without git installed.
  REPO_PATH="${STANDARDS_REPO#https://github.com/}"
  REPO_PATH="${REPO_PATH%.git}"
  curl -fsSL "https://codeload.github.com/${REPO_PATH}/tar.gz/${REF}" \
    | tar -xz -C "$TMP"
  mv "$TMP"/*-"${REF}"* "$TMP/src" 2>/dev/null || mv "$TMP"/*/ "$TMP/src"
  RESOLVED_SHA="$REF"
else
  echo "✗ Need 'git' or 'curl + tar' to fetch the standards repo." >&2
  exit 1
fi

if [[ ! -d "$TMP/src/skills" || ! -d "$TMP/src/standards" ]]; then
  echo "✗ Fetched archive is missing 'skills/' or 'standards/'." >&2
  exit 1
fi

# --- Skills ---------------------------------------------------------------
SKILLS_DIR="$TARGET/.claude/skills"
mkdir -p "$SKILLS_DIR"

echo "→ Installing skills into .claude/skills/"
# Use rsync if available for cleaner output; otherwise cp -R.
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete-excluded "$TMP/src/skills/" "$SKILLS_DIR/"
else
  cp -R "$TMP/src/skills/." "$SKILLS_DIR/"
fi

SKILL_COUNT="$(find "$SKILLS_DIR" -name SKILL.md -type f | wc -l | tr -d ' ')"
echo "  installed ${SKILL_COUNT} skills"

# --- Standards → AGENTS.md ------------------------------------------------
AGENTS_FILE="$TARGET/AGENTS.md"

if [[ -f "$AGENTS_FILE" && "$FORCE" != "1" ]]; then
  if ! head -n 1 "$AGENTS_FILE" | grep -q "AUTO-GENERATED from my-agent-skills"; then
    echo "✗ $AGENTS_FILE exists and was not generated by this script." >&2
    echo "  Set FORCE=1 to overwrite, or move the existing file aside." >&2
    exit 1
  fi
fi

echo "→ Writing AGENTS.md"
{
  echo "<!-- AUTO-GENERATED from my-agent-skills@${RESOLVED_SHA} -->"
  echo "<!-- Source: ${STANDARDS_REPO} -->"
  echo "<!-- Do not edit by hand. Re-run install.sh to update. -->"
  echo
  # Lexicographic ordering (00-, 01-, 02-...) gives deterministic precedence.
  for f in "$TMP"/src/standards/*.md; do
    [[ -e "$f" ]] || continue
    echo "<!-- source: $(basename "$f") -->"
    cat "$f"
    echo
    echo
  done
} > "$AGENTS_FILE"

echo
echo "✓ Done."
echo
echo "Next steps:"
echo "  1. In your CLAUDE.md, add the line:  @AGENTS.md"
echo "  2. Commit .claude/skills/ and AGENTS.md to your repo."
echo "  3. Re-run this script to pull updates from upstream."
